#!/bin/bash 
to_gbgt() {
  local expr="$1"

  # Map abbreviations to IANA zones
  local tz=""
  case "$expr" in
    *PST*|*PDT*|*PT*)   tz="America/Los_Angeles" ;;
    *MST*|*MDT*|*MT*)   tz="America/Denver" ;;
    *CST*|*CDT*|*CT*)   tz="America/Chicago" ;;
    *EST*|*EDT*|*ET*)   tz="America/New_York" ;;
    *UTC*|*GMT*|*Z)     tz="UTC" ;;
    *BST*)              tz="Europe/London" ;;
    *CET*|*CEST*)       tz="Europe/Stockholm" ;;
  esac

  # Default to Gothenburg if no zone detected
  : ${tz:=Europe/Stockholm}

  # Strip known timezone abbrevs from the input for clean date parsing
  local clean_expr
  clean_expr=$(echo "$expr" |
    sed -E '
      s/[[:space:]]+(EST|EDT|CST|CDT|MST|MDT|PST|PDT|ET|CT|MT|PT|GMT|UTC|Z|CET|CEST|BST)[[:space:]]*/ /Ig;
      s/\b([0-9]{1,2})(st|nd|rd|th)\b/\1/Ig;
      s/\bat\b/ /Ig;
      s/^ +| +$//g
    ')

  if ! ts=$(TZ="$tz" date -d "$clean_expr" +%s 2>/dev/null); then
    echo "Unable to parse: $expr" >&2
    return 1
  fi

  TZ="Europe/Stockholm" date -d "@$ts" "+%Y-%m-%d %H:%M"
}
